packages:
  package: !include common/treatlife_3way_ss01.yaml

substitutions:
  device_name: "basement-stairs-top-light"
  pretty_name: "Basement Stairs Top Lightswitch"
  ui_name: "Basement Stairs Light"
  icon: "mdi:lghtbulb"
