packages:
  package: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "bedroom-lightswitch"
  pretty_name: "Bedroom Lightswitch"
  ui_name: "Bedroom Light"
  icon: "mdi:lghtbulb"