packages:
  package: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "hallway-lightswitch"
  pretty_name: "Hallway Lightswitch"
  ui_name: "Hallway Light"
  icon: "mdi:lghtbulb"