packages:
  package: !include common/treatlife_3way_ss01.yaml

substitutions:
  device_name: "kitchen-west-lightswitch"
  pretty_name: "Kitchen West Lightswitch"
  ui_name: "Kitchen Light"
  icon: "mdi:lghtbulb"
