packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "kitchen-blue-accent-light"
  pretty_name: "Kitchen Blue Accent Light"
  ui_name: "Kitchen Blue Accent Light"
  icon: "mdi:lghtbulb"
