packages:
  package: !include common/h801_rgb.yaml

substitutions:
  device_name: "living-room-tv-rgb"
  pretty_name: "Living Room TV RGB"
  light_restore_mode: RESTORE_DEFAULT_OFF

# esphome:
# on_boot:
#     then:
#     - light.control:
#         id: light_1
