packages:
  package: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "outside-floodlight"
  pretty_name: "Outside Floodlight"
  ui_name: "Outside Floodlight"
  icon: "mdi:lghtbulb"