packages:
  base: !include common/sensor_board_base.yaml
  base_components: !include common/packages/esp_home_components.yaml
substitutions:
  device_name: "sensor-condensate-alarm"
  pretty_name: "Condensate Pump Alarm"
  ui_name: "${pretty_name}"
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO4
      inverted: true
      mode: INPUT_PULLUP
    name: "${pretty_name} Full"
    device_class: Moisture
