packages:
  package: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "upstairs-ceiling-lightswitch"
  pretty_name: "Upstairs Ceiling Lightswitch"
  ui_name: "Upstairs Ceiling Light"
  icon: "mdi:lghtbulb"